/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.org.loanledger;

import java.io.*;

import com.org.loanledger.factory.RequestFactory;
import com.org.loanledger.request.AbstractRequest;
import com.org.loanledger.request.Request;
import com.org.loanledger.service.ServiceManager;

public class App {

	public static void main(String[] args) {
		if (args == null || args[0] == null || args[0] == "") {
			throw new IllegalArgumentException("file path not passed");
		}
		File file = new File(args[0]);
		try (BufferedReader br = new BufferedReader(new FileReader(file))) {
			String line = br.readLine();
			while (line != null) {
				//request obj can be of Loan,balanceCheck and Payment
				AbstractRequest request = RequestFactory.getRequest(line);
				try {
					switch (request.getRequestType()) {
						case LOAN:
							ServiceManager.getLedgerService().bookLoan(request);
							break;
						case LUMPSUM_PAYMENT:
							ServiceManager.getLedgerService().makePayment(request);
							break;
						case BALANCE:
							String result = ServiceManager.getLedgerService().checkBalance(request);
							System.out.println(result);
							break;
						default:
							break;
					}
				} catch (Exception e) {
					e.printStackTrace();
				}
				line = br.readLine();
			}

		} catch (FileNotFoundException e) {

		} catch (IOException e) {
			throw new RuntimeException(e);
		}

	}
}
